[features]
seeds = false
skip-lint = false
[programs.localnet]
taxovate = "5FCuQ3GBv3d1GWropp9t1fW6yLSnqBdSKFU3yfSCjC63"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kunalbagaria/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
